/* ============================================
   MPS Platform — Widget Catalog
   Metadata for all report builder widgets
   ============================================ */

import {
  Package,
  DollarSign,
  ShieldCheck,
  Recycle,
  BarChart3,
  TrendingUp,
  PieChart,
  ListOrdered,
  Layers,
  Building2,
  Table2,
  FileSpreadsheet,
  MapPin,
  StickyNote,
  Activity,
  HardHat,
  Monitor,
  Heart,
  AreaChart,
  Grid3X3,
  Factory,
  Leaf,
  Target,
  TreePine,
  AlertTriangle,
  Clock,
  Route,
  DatabaseZap,
} from "lucide-react";
import type { WidgetDefinition, SectionCategory } from "./report-builder-types";

export const WIDGET_CATALOG: WidgetDefinition[] = [
  // KPI blocks
  {
    type: "kpi-waste-volume",
    label: "Waste Volume Summary",
    description: "Total tons, shipments, avg load, container utilization",
    category: "kpi",
    icon: Package,
    defaultConfig: {},
  },
  {
    type: "kpi-cost-summary",
    label: "Cost Summary",
    description: "MPS cost, customer revenue, margin, cost per ton",
    category: "kpi",
    icon: DollarSign,
    defaultConfig: {},
  },
  {
    type: "kpi-compliance",
    label: "Compliance Summary",
    description: "Manifest coverage, hazardous %, on-time rate",
    category: "kpi",
    icon: ShieldCheck,
    defaultConfig: {},
  },
  {
    type: "kpi-diversion",
    label: "Diversion Summary",
    description: "Diversion rate, recycling tons, landfill tons",
    category: "kpi",
    icon: Recycle,
    defaultConfig: {},
  },
  {
    type: "kpi-operational",
    label: "Operational Metrics",
    description: "Avg miles, target vs actual, active sites",
    category: "kpi",
    icon: Activity,
    defaultConfig: {},
  },
  {
    type: "kpi-safety",
    label: "Safety Metrics",
    description: "TRIR, incidents, resolved %, training completion",
    category: "kpi",
    icon: HardHat,
    defaultConfig: {},
  },
  {
    type: "kpi-platform",
    label: "Platform Analytics",
    description: "Monthly active users, adoption rate, utilization",
    category: "kpi",
    icon: Monitor,
    defaultConfig: {},
  },
  {
    type: "kpi-customer",
    label: "Customer Experience",
    description: "CSAT, NPS, first contact resolution",
    category: "kpi",
    icon: Heart,
    defaultConfig: {},
  },
  // Charts
  {
    type: "chart-volume-trend",
    label: "Volume Trend",
    description: "Monthly tonnage bar chart over time",
    category: "chart",
    icon: BarChart3,
    defaultConfig: {},
  },
  {
    type: "chart-cost-comparison",
    label: "Cost Comparison",
    description: "MPS cost vs customer revenue by month",
    category: "chart",
    icon: TrendingUp,
    defaultConfig: {},
  },
  {
    type: "chart-waste-donut",
    label: "Waste Distribution",
    description: "Donut chart by waste category",
    category: "chart",
    icon: PieChart,
    defaultConfig: {},
  },
  {
    type: "chart-top-streams",
    label: "Top Waste Streams",
    description: "Top 10 waste streams by volume",
    category: "chart",
    icon: ListOrdered,
    defaultConfig: {},
  },
  {
    type: "chart-cost-waterfall",
    label: "Cost Waterfall",
    description: "Revenue to net margin flow breakdown",
    category: "chart",
    icon: Layers,
    defaultConfig: {},
  },
  {
    type: "chart-vendor-spend",
    label: "Vendor Spend",
    description: "Cost distribution by vendor",
    category: "chart",
    icon: Building2,
    defaultConfig: {},
  },
  {
    type: "chart-cost-composition",
    label: "Cost Composition",
    description: "Stacked area — monthly cost breakdown by category",
    category: "chart",
    icon: AreaChart,
    defaultConfig: {},
  },
  {
    type: "chart-margin-heatmap",
    label: "Margin Heatmap",
    description: "Site × waste type margin matrix with color coding",
    category: "chart",
    icon: Grid3X3,
    defaultConfig: {},
  },
  {
    type: "chart-ghg-emissions",
    label: "GHG Emissions",
    description: "Greenhouse gas by waste category — emissions vs offsets",
    category: "chart",
    icon: Factory,
    defaultConfig: {},
  },
  {
    type: "chart-diversion-trend",
    label: "Diversion Trend",
    description: "Monthly landfill diversion rate area chart",
    category: "chart",
    icon: Leaf,
    defaultConfig: {},
  },
  {
    type: "chart-efficiency-scatter",
    label: "Load Efficiency",
    description: "Actual vs target load weight scatter plot",
    category: "chart",
    icon: Target,
    defaultConfig: {},
  },
  {
    type: "chart-treemap",
    label: "Waste Treemap",
    description: "Proportional volume by waste type",
    category: "chart",
    icon: TreePine,
    defaultConfig: {},
  },
  {
    type: "chart-incident-trend",
    label: "Incident Trend",
    description: "Monthly safety incidents area chart",
    category: "chart",
    icon: AlertTriangle,
    defaultConfig: {},
  },
  {
    type: "chart-csat-trend",
    label: "CSAT & NPS Trend",
    description: "Monthly customer satisfaction and net promoter score",
    category: "chart",
    icon: Heart,
    defaultConfig: {},
  },
  {
    type: "chart-ar-aging",
    label: "AR Aging",
    description: "Outstanding invoice amounts by days overdue",
    category: "chart",
    icon: Clock,
    defaultConfig: {},
  },
  {
    type: "chart-facility-utilization",
    label: "Facility Utilization",
    description: "Receiving facility capacity usage with thresholds",
    category: "chart",
    icon: Route,
    defaultConfig: {},
  },
  // Tables
  {
    type: "table-shipment-detail",
    label: "Shipment Detail",
    description: "Detailed shipment records with key fields",
    category: "table",
    icon: Table2,
    defaultConfig: { tableRowLimit: 25 },
  },
  {
    type: "table-waste-summary",
    label: "Waste Stream Summary",
    description: "Aggregated by waste type — tons, shipments, cost",
    category: "table",
    icon: FileSpreadsheet,
    defaultConfig: { tableRowLimit: 25 },
  },
  {
    type: "table-cost-by-site",
    label: "Cost by Site",
    description: "Site-level cost and revenue rollup",
    category: "table",
    icon: MapPin,
    defaultConfig: { tableRowLimit: 25 },
  },
  {
    type: "table-route-margin",
    label: "Route Margin",
    description: "Profit per route — site to transporter",
    category: "table",
    icon: Route,
    defaultConfig: { tableRowLimit: 25 },
  },
  {
    type: "table-vendor-risk",
    label: "Vendor Risk Matrix",
    description: "Vendor risk levels, shipments, cost, DBE status",
    category: "table",
    icon: ShieldCheck,
    defaultConfig: { tableRowLimit: 25 },
  },
  {
    type: "table-quality-breakdown",
    label: "Quality Breakdown",
    description: "Data quality checks — missing fields and issue rates",
    category: "table",
    icon: DatabaseZap,
    defaultConfig: { tableRowLimit: 25 },
  },
  // Content
  {
    type: "notes-block",
    label: "Notes / Commentary",
    description: "Free-text block for analyst notes",
    category: "content",
    icon: StickyNote,
    defaultConfig: { notes: "" },
  },
];

export const CATEGORY_LABELS: Record<SectionCategory, string> = {
  kpi: "Key Metrics",
  chart: "Charts",
  table: "Data Tables",
  content: "Content",
};

export const CATEGORY_ORDER: SectionCategory[] = ["kpi", "chart", "table", "content"];

export function getWidgetDefinition(type: string): WidgetDefinition | undefined {
  return WIDGET_CATALOG.find((w) => w.type === type);
}
